ssl_storage_port: 7001
storage_port: 7000
continuous_paging:
  max_concurrent_sessions: 60
  max_session_pages: 4
  max_page_size_mb: 8
  max_client_wait_time_ms: 20000
  max_local_query_time_ms: 5000
  max_threads: 24
batchlog_replay_throttle_in_kb: 1024
commit_failure_policy: stop
unlogged_batch_across_partitions_warn_threshold: 10
native_transport_max_frame_size_in_mb: 256
commitlog_segment_size_in_mb: 2
commitlog_total_space_in_mb: 10
commitlog_directory: /var/lib/cassandra/commitlog
commitlog_sync_period_in_ms: 10000
commitlog_sync: periodic
cdc_enabled: true
cdc_total_space_in_mb: 1024
cdc_raw_directory: /var/lib/cassandra/cdc_raw
cdc_free_space_check_interval_ms: 250
memtable_flush_writers: 4
memtable_heap_space_in_mb: 2048
memtable_allocation_type: heap_buffers
memtable_offheap_space_in_mb: 2048
start_rpc: true
allocate_tokens_for_local_replication_factor: 3
credentials_validity_in_ms: 2000
client_encryption_options:
  enabled: false
concurrent_materialized_view_writes: 32
disk_access_mode: mmap_index_only
inter_dc_tcp_nodelay: false
column_index_cache_size_in_kb: 2
internode_authenticator: org.apache.cassandra.auth.AllowAllInternodeAuthenticator
rpc_server_type: sync
max_value_size_in_mb: 256
authorizer: AllowAllAuthorizer
num_tokens: 8
listen_on_broadcast_address: false
row_cache_save_period: 0
row_cache_class_name: org.apache.cassandra.cache.OHCProvider
disk_failure_policy: stop
native_transport_port: 9042
server_encryption_options:
  internode_encryption: none
dynamic_snitch_reset_interval_in_ms: 600000
compaction_throughput_mb_per_sec: 64
data_file_directories:
- /var/lib/cassandra/data
role_manager: com.datastax.bdp.cassandra.auth.DseRoleManager
column_index_size_in_kb: 64
batch_size_warn_threshold_in_kb: 5
windows_timer_interval: 1
compaction_large_partition_warning_threshold_mb: 100
rpc_keepalive: true
batch_size_fail_threshold_in_kb: 50
snapshot_before_compaction: false
tracetype_query_ttl: 86400
concurrent_reads: 32
key_cache_save_period: 14400
row_cache_size_in_mb: 0
tracetype_repair_ttl: 604800
tombstone_warn_threshold: 1000
request_scheduler_options:
  throttle_limit: 80
  default_weight: 5
auto_bootstrap: true
rpc_address: 127.0.0.1
concurrent_writes: 32
disk_optimization_strategy: ssd
counter_cache_save_period: 7200
file_cache_size_in_mb: 768
back_pressure_enabled: false
slow_query_log_timeout_in_ms: 500
trickle_fsync: true
streaming_keep_alive_period_in_secs: 300
write_request_timeout_in_ms: 2000
initial_token: null
incremental_backups: false
truncate_request_timeout_in_ms: 60000
snapshot_before_dropping_column: false
enable_scripted_user_defined_functions: false
read_request_timeout_in_ms: 5000
request_timeout_in_ms: 10000
start_native_transport: true
saved_caches_directory: /var/lib/cassandra/saved_caches
transparent_data_encryption_options:
  enabled: false
  chunk_length_kb: 64
  cipher: AES/CBC/PKCS5Padding
  key_alias: testing:1
internode_compression: dc
authenticator: AllowAllAuthenticator
phi_convict_threshold: 8
max_hints_delivery_threads: 2
cross_node_timeout: false
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
tombstone_failure_threshold: 100000
buffer_pool_use_heap_if_exhausted: true
hinted_handoff_enabled: true
concurrent_compactors: 2
hints_flush_period_in_ms: 10000
enable_user_defined_functions: false
hinted_handoff_throttle_in_kb: 1024
max_hint_window_in_ms: 10800000
otc_coalescing_strategy: DISABLED
broadcast_rpc_address: 127.0.0.1
auto_snapshot: true
index_summary_resize_interval_in_minutes: 60
range_request_timeout_in_ms: 10000
stream_throughput_outbound_megabits_per_sec: 200
sstable_preemptive_open_interval_in_mb: 50
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: "127.0.0.1"
dynamic_snitch_update_interval_in_ms: 100
native_transport_max_threads: 128
trickle_fsync_interval_in_kb: 10240
listen_address: 127.0.0.1
max_hints_file_size_in_mb: 128
counter_write_request_timeout_in_ms: 5000
cluster_name: DigiCertCluster
echo_attempts_before_reset: 10
concurrent_counter_writes: 32
endpoint_snitch: GossipingPropertyFileSnitch
cross_dc_rtt_in_ms: 0
hints_directory: /var/lib/cassandra/hints
dynamic_snitch_badness_threshold: 0.1
native_transport_max_concurrent_connections_per_ip: -1
broadcast_address: 127.0.0.1
permissions_validity_in_ms: 2000
roles_validity_in_ms: 2000
rpc_port: 9160
otc_backlog_expiration_interval_ms: 200
cas_contention_timeout_in_ms: 1000
seed_gossip_probability: 1.0
thrift_framed_transport_size_in_mb: 15
native_transport_max_concurrent_connections: -1
gc_warn_threshold_in_ms: 1000
aggregated_request_timeout_in_ms: 120000
request_scheduler: org.apache.cassandra.scheduler.NoScheduler
