version: '3.3'
services:   
  cassandra:
    container_name: cassandra
    image: datastax/dse-server:5.1.24
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_YAML=/opt/dse/resources/cassandra/conf
      - DEBEZIUM_HOME=/opt/dse/resources/debezium
    ports:
      - "0.0.0.0:9052:9042"
    links:
      - zookeeper
      - kafka
    volumes:
      - ./dse/configs/:/config/    
      - ./dse/configs/:/home/
      # - ./mnt/cassandra/:/var/lib/cassandra/
  ds-studio:
    container_name: ds-studio
    image: datastax/dse-studio
    ports:
      - 9091:9091
    links:
      - cassandra
    environment:
      - DS_LICENSE=accept 
    volumes:
      - ./mnt/ds-studio/:/var/lib/datastax-studio/
  mysql_target_db:
    container_name: mysql_target_db
    image: mariadb:10.3.24-focal
    environment: 
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=digicert_com
        - MYSQL_USER=debezium
        - MYSQL_PASSWORD=debezium
    volumes:
        - ./mnt/mysql:/var/lib/mysql
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
        - "0.0.0.0:3316:3306"
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.6
    ports:
      - "0.0.0.0:2181:2181"
      - "0.0.0.0:2888:2888"
      - "0.0.0.0:3888:3888"
    volumes: 
        - ./mnt/zookeeper/data:/zookeeper/data
        - ./mnt/zookeeper/logs:/zookeeper/logs
        - ./mnt/zookeeper/txns:/zookeeper/txns      
  kafka:
    container_name: kafka
    image: debezium/kafka:1.6
    ports:
      - "0.0.0.0:9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181/kafka
    volumes: 
        - ./mnt/kafka/data:/kafka/data
        - ./mnt/kafka/logs:/kafka/logs          
  kafka_manager:
    container_name: kafka_manager
    image: hlebalbau/kafka-manager:1.3.3.18
    ports:      
        - "0.0.0.0:9000:9000"
    environment:
        ZK_HOSTS: "zookeeper:2181"
        APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null          
  connect:
    container_name: connect
    image: anieshaz/connect:1.0
    ports:
      - "0.0.0.0:8083:8083"
      - "0.0.0.0:5005:5005"
    links:
      - mysql_target_db
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
  connect_ui:
    container_name: connect_ui
    image: landoop/kafka-connect-ui
    ports:
      - "0.0.0.0:8003:8000"
    environment:
      - CONNECT_URL=http://connect:8083
    depends_on:
      - connect
  # schema_registry:
  #   container_name: schema_registry
  #   image: confluentinc/cp-schema-registry
  #   ports:
  #       - "0.0.0.0:8100:8181"
  #   environment: 
  #       # - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
  #       - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092
  #       - SCHEMA_REGISTRY_HOST_NAME=schema-registry
  #       - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
  #   links:
  #       - zookeeper
  # cdata-sync:
  #   container_name: cdata-sync
  #   image: registry.de.dev.blu.digicert.com/cdata-sync:1.0
  #   ports:
  #     - "0.0.0.0:8400:8443"
  #   volumes:
  #     - ./cdata/var/opt/sync/libs/:/var/opt/sync/libs
  #     - ./cdata/opt/cdata/sync:/opt/cdata/sync