/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `certopedia` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `certopedia`;

CREATE TABLE IF NOT EXISTS `import_failures` (
  `cert_id` int(10) unsigned NOT NULL,
  `ca_id` mediumint(8) unsigned DEFAULT NULL,
  `serial` varchar(32) NOT NULL DEFAULT '',
  `cert_type` tinyint(3) unsigned DEFAULT NULL,
  `issue_date` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `pem` mediumtext DEFAULT NULL,
  `err` mediumtext DEFAULT NULL,
  PRIMARY KEY (`cert_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `issuers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ca_id` int(10) unsigned DEFAULT 0,
  `auth_key_id` varchar(40) DEFAULT '',
  `issuer_org` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `issuer_cn` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `issuer_cc` varchar(4) DEFAULT '' COMMENT 'country_code',
  `ca_issuer_url` varchar(200) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10300 DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `revokes` (
  `cert_id` int(10) unsigned NOT NULL,
  `revoke_reason` tinyint(4) DEFAULT NULL,
  `revoke_date_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `comments` varchar(200) NOT NULL,
  `soft_revoke_ended` varchar(200) DEFAULT '',
  UNIQUE KEY `u_idx_cert_id` (`cert_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `v_certs_issued_weekly` (
	`id` INT(10) UNSIGNED NOT NULL,
	`issuer_id` MEDIUMINT(8) UNSIGNED NOT NULL,
	`sha1_hash` VARCHAR(40) NOT NULL COLLATE 'ascii_general_ci',
	`sha256_hash` VARCHAR(64) NOT NULL COLLATE 'ascii_general_ci',
	`serial_number` VARCHAR(40) NOT NULL COLLATE 'ascii_general_ci',
	`key_type` ENUM('','RSA','DSA','DH','EC') NOT NULL COLLATE 'ascii_general_ci',
	`key_size` SMALLINT(5) UNSIGNED NOT NULL,
	`issue_date_gmt` DATETIME NOT NULL,
	`valid_from_gmt` DATETIME NOT NULL,
	`valid_to_gmt` DATETIME NOT NULL,
	`subject_cn` VARCHAR(128) NULL COLLATE 'utf8_general_ci',
	`subject_org` VARCHAR(128) NULL COLLATE 'utf8_general_ci',
	`subject_ou` VARCHAR(255) NULL COLLATE 'utf8_general_ci',
	`subject_state` VARCHAR(96) NULL COLLATE 'utf8_general_ci',
	`subject_locale` VARCHAR(96) NULL COLLATE 'utf8_general_ci',
	`subject_country` VARCHAR(4) NULL COLLATE 'ascii_general_ci',
	`subject_jur` VARCHAR(255) NULL COLLATE 'ascii_general_ci',
	`subject_addr` VARCHAR(255) NULL COLLATE 'ascii_general_ci',
	`subject_key_id` VARCHAR(40) NULL COLLATE 'ascii_general_ci',
	`sig_hash` ENUM('other','md5','sha1','sha256','sha384','sha512','sha256ecdsa','sha384ecdsa','sha512ecdsa') NOT NULL COLLATE 'ascii_general_ci',
	`ku` SET('digitalSignature','nonRepudiation','keyEncipherment','dataEncipherment','keyAgreement','keyCertSign','cRLSign','encipherOnly','decipherOnly','critical') NOT NULL COLLATE 'ascii_general_ci',
	`eku` SET('other','critical','serverAuth','clientAuth','codeSigning','emailProtection','anyExtendedKeyUsage','timeStamping','ocspSigning','ipsecEndSystem','ipsecTunnel','ipsecUser','ipsecProtection','ipsecIKE','nsSGC','msSGC','msEFS','msSmartcardLogin','msCTLSign','msCodeInd','msCodeCom','msDocSigning','keyPurposeKdc','intelAMTProvisioning') NOT NULL COLLATE 'ascii_general_ci',
	`validation` ENUM('OTHER','OV','OVCF','EV') NOT NULL COLLATE 'ascii_general_ci',
	`cert_type` VARCHAR(6) NULL COLLATE 'ascii_general_ci',
	`crl_url_id` MEDIUMINT(8) UNSIGNED NOT NULL,
	`ocsp_url_id` MEDIUMINT(8) UNSIGNED NOT NULL,
	`policies_id` MEDIUMINT(8) UNSIGNED NOT NULL,
	`sans` MEDIUMTEXT NOT NULL COLLATE 'ascii_general_ci'
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS `xcerts_2015` (
  `id` int(10) unsigned NOT NULL,
  `issuer_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sha1_hash` varchar(40) NOT NULL DEFAULT '',
  `sha256_hash` varchar(64) NOT NULL DEFAULT '',
  `serial_number` varchar(40) NOT NULL DEFAULT '',
  `key_type` enum('','RSA','DSA','DH','EC') NOT NULL DEFAULT '',
  `key_size` smallint(5) unsigned NOT NULL DEFAULT 0,
  `issue_date_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_from_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_to_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `subject_cn` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_org` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_ou` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `subject_state` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_locale` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_country` varchar(4) DEFAULT '',
  `subject_jur` varchar(255) DEFAULT '',
  `subject_addr` varchar(255) DEFAULT '',
  `subject_key_id` varchar(40) DEFAULT '',
  `sig_hash` enum('other','md5','sha1','sha256','sha384','sha512','sha256ecdsa','sha384ecdsa','sha512ecdsa') NOT NULL DEFAULT 'other',
  `ku` set('digitalSignature','nonRepudiation','keyEncipherment','dataEncipherment','keyAgreement','keyCertSign','cRLSign','encipherOnly','decipherOnly','critical') NOT NULL DEFAULT '',
  `eku` set('other','critical','serverAuth','clientAuth','codeSigning','emailProtection','anyExtendedKeyUsage','timeStamping','ocspSigning','ipsecEndSystem','ipsecTunnel','ipsecUser','ipsecProtection','ipsecIKE','nsSGC','msSGC','msEFS','msSmartcardLogin','msCTLSign','msCodeInd','msCodeCom','msDocSigning','keyPurposeKdc','intelAMTProvisioning') NOT NULL DEFAULT '',
  `validation` enum('OTHER','OV','OVCF','EV') NOT NULL DEFAULT 'OTHER',
  `cert_type` varchar(6) GENERATED ALWAYS AS (case when find_in_set('serverAuth',`eku`) then 'SSL' when find_in_set('codeSigning',`eku`) then 'CS' when find_in_set('emailProtection',`eku`) then 'SMIME' when `eku` = 'clientAuth' then 'CLIENT' else 'OTHER' end) VIRTUAL,
  `crl_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `ocsp_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `policies_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sans` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `issuer_id` (`issuer_id`),
  KEY `serial_number` (`serial_number`(8)),
  KEY `issue_date_gmt` (`issue_date_gmt`),
  KEY `valid_from_gmt` (`valid_from_gmt`),
  KEY `valid_to_gmt` (`valid_to_gmt`),
  KEY `validation` (`validation`),
  KEY `subject_country` (`subject_country`(2)),
  KEY `subject_org` (`subject_org`(8)),
  KEY `subject_cn` (`subject_cn`(8)),
  KEY `sha1_hash` (`sha1_hash`(8)),
  KEY `sha256_hash` (`sha256_hash`(8))
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `xcerts_2016` (
  `id` int(10) unsigned NOT NULL,
  `issuer_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sha1_hash` varchar(40) NOT NULL DEFAULT '',
  `sha256_hash` varchar(64) NOT NULL DEFAULT '',
  `serial_number` varchar(40) NOT NULL DEFAULT '',
  `key_type` enum('','RSA','DSA','DH','EC') NOT NULL DEFAULT '',
  `key_size` smallint(5) unsigned NOT NULL DEFAULT 0,
  `issue_date_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_from_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_to_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `subject_cn` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_org` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_ou` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `subject_state` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_locale` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_country` varchar(4) DEFAULT '',
  `subject_jur` varchar(255) DEFAULT '',
  `subject_addr` varchar(255) DEFAULT '',
  `subject_key_id` varchar(40) DEFAULT '',
  `sig_hash` enum('other','md5','sha1','sha256','sha384','sha512','sha256ecdsa','sha384ecdsa','sha512ecdsa') NOT NULL DEFAULT 'other',
  `ku` set('digitalSignature','nonRepudiation','keyEncipherment','dataEncipherment','keyAgreement','keyCertSign','cRLSign','encipherOnly','decipherOnly','critical') NOT NULL DEFAULT '',
  `eku` set('other','critical','serverAuth','clientAuth','codeSigning','emailProtection','anyExtendedKeyUsage','timeStamping','ocspSigning','ipsecEndSystem','ipsecTunnel','ipsecUser','ipsecProtection','ipsecIKE','nsSGC','msSGC','msEFS','msSmartcardLogin','msCTLSign','msCodeInd','msCodeCom','msDocSigning','keyPurposeKdc','intelAMTProvisioning') NOT NULL DEFAULT '',
  `validation` enum('OTHER','OV','OVCF','EV') NOT NULL DEFAULT 'OTHER',
  `cert_type` varchar(6) GENERATED ALWAYS AS (case when find_in_set('serverAuth',`eku`) then 'SSL' when find_in_set('codeSigning',`eku`) then 'CS' when find_in_set('emailProtection',`eku`) then 'SMIME' when `eku` = 'clientAuth' then 'CLIENT' else 'OTHER' end) VIRTUAL,
  `crl_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `ocsp_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `policies_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sans` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `issuer_id` (`issuer_id`),
  KEY `serial_number` (`serial_number`(8)),
  KEY `issue_date_gmt` (`issue_date_gmt`),
  KEY `valid_from_gmt` (`valid_from_gmt`),
  KEY `valid_to_gmt` (`valid_to_gmt`),
  KEY `validation` (`validation`),
  KEY `subject_country` (`subject_country`(2)),
  KEY `subject_org` (`subject_org`(8)),
  KEY `subject_cn` (`subject_cn`(8)),
  KEY `sha1_hash` (`sha1_hash`(8)),
  KEY `sha256_hash` (`sha256_hash`(8))
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `xcerts_2017` (
  `id` int(10) unsigned NOT NULL,
  `issuer_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sha1_hash` varchar(40) NOT NULL DEFAULT '',
  `sha256_hash` varchar(64) NOT NULL DEFAULT '',
  `serial_number` varchar(40) NOT NULL DEFAULT '',
  `key_type` enum('','RSA','DSA','DH','EC') NOT NULL DEFAULT '',
  `key_size` smallint(5) unsigned NOT NULL DEFAULT 0,
  `issue_date_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_from_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_to_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `subject_cn` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_org` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_ou` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `subject_state` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_locale` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_country` varchar(4) DEFAULT '',
  `subject_jur` varchar(255) DEFAULT '',
  `subject_addr` varchar(255) DEFAULT '',
  `subject_key_id` varchar(40) DEFAULT '',
  `sig_hash` enum('other','md5','sha1','sha256','sha384','sha512','sha256ecdsa','sha384ecdsa','sha512ecdsa') NOT NULL DEFAULT 'other',
  `ku` set('digitalSignature','nonRepudiation','keyEncipherment','dataEncipherment','keyAgreement','keyCertSign','cRLSign','encipherOnly','decipherOnly','critical') NOT NULL DEFAULT '',
  `eku` set('other','critical','serverAuth','clientAuth','codeSigning','emailProtection','anyExtendedKeyUsage','timeStamping','ocspSigning','ipsecEndSystem','ipsecTunnel','ipsecUser','ipsecProtection','ipsecIKE','nsSGC','msSGC','msEFS','msSmartcardLogin','msCTLSign','msCodeInd','msCodeCom','msDocSigning','keyPurposeKdc','intelAMTProvisioning') NOT NULL DEFAULT '',
  `validation` enum('OTHER','OV','OVCF','EV') NOT NULL DEFAULT 'OTHER',
  `cert_type` varchar(6) GENERATED ALWAYS AS (case when find_in_set('serverAuth',`eku`) then 'SSL' when find_in_set('codeSigning',`eku`) then 'CS' when find_in_set('emailProtection',`eku`) then 'SMIME' when `eku` = 'clientAuth' then 'CLIENT' else 'OTHER' end) VIRTUAL,
  `crl_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `ocsp_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `policies_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sans` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `issuer_id` (`issuer_id`),
  KEY `serial_number` (`serial_number`(8)),
  KEY `issue_date_gmt` (`issue_date_gmt`),
  KEY `valid_from_gmt` (`valid_from_gmt`),
  KEY `valid_to_gmt` (`valid_to_gmt`),
  KEY `validation` (`validation`),
  KEY `subject_country` (`subject_country`(2)),
  KEY `subject_org` (`subject_org`(8)),
  KEY `subject_cn` (`subject_cn`(8)),
  KEY `sha1_hash` (`sha1_hash`(8)),
  KEY `sha256_hash` (`sha256_hash`(8))
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `xcerts_2018` (
  `id` int(10) unsigned NOT NULL,
  `issuer_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sha1_hash` varchar(40) NOT NULL DEFAULT '',
  `sha256_hash` varchar(64) NOT NULL DEFAULT '',
  `serial_number` varchar(40) NOT NULL DEFAULT '',
  `key_type` enum('','RSA','DSA','DH','EC') NOT NULL DEFAULT '',
  `key_size` smallint(5) unsigned NOT NULL DEFAULT 0,
  `issue_date_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_from_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_to_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `subject_cn` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_org` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_ou` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `subject_state` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_locale` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_country` varchar(4) DEFAULT '',
  `subject_jur` varchar(255) DEFAULT '',
  `subject_addr` varchar(255) DEFAULT '',
  `subject_key_id` varchar(40) DEFAULT '',
  `sig_hash` enum('other','md5','sha1','sha256','sha384','sha512','sha256ecdsa','sha384ecdsa','sha512ecdsa') NOT NULL DEFAULT 'other',
  `ku` set('digitalSignature','nonRepudiation','keyEncipherment','dataEncipherment','keyAgreement','keyCertSign','cRLSign','encipherOnly','decipherOnly','critical') NOT NULL DEFAULT '',
  `eku` set('other','critical','serverAuth','clientAuth','codeSigning','emailProtection','anyExtendedKeyUsage','timeStamping','ocspSigning','ipsecEndSystem','ipsecTunnel','ipsecUser','ipsecProtection','ipsecIKE','nsSGC','msSGC','msEFS','msSmartcardLogin','msCTLSign','msCodeInd','msCodeCom','msDocSigning','keyPurposeKdc','intelAMTProvisioning') NOT NULL DEFAULT '',
  `validation` enum('OTHER','OV','OVCF','EV') NOT NULL DEFAULT 'OTHER',
  `cert_type` varchar(6) GENERATED ALWAYS AS (case when find_in_set('serverAuth',`eku`) then 'SSL' when find_in_set('codeSigning',`eku`) then 'CS' when find_in_set('emailProtection',`eku`) then 'SMIME' when `eku` = 'clientAuth' then 'CLIENT' else 'OTHER' end) VIRTUAL,
  `crl_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `ocsp_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `policies_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sans` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `issuer_id` (`issuer_id`),
  KEY `serial_number` (`serial_number`(8)),
  KEY `issue_date_gmt` (`issue_date_gmt`),
  KEY `valid_from_gmt` (`valid_from_gmt`),
  KEY `valid_to_gmt` (`valid_to_gmt`),
  KEY `validation` (`validation`),
  KEY `subject_country` (`subject_country`(2)),
  KEY `subject_org` (`subject_org`(8)),
  KEY `subject_cn` (`subject_cn`(8)),
  KEY `sha1_hash` (`sha1_hash`(8)),
  KEY `sha256_hash` (`sha256_hash`(8)),
  KEY `_idx_cert_type` (`cert_type`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `xcerts_2019` (
  `id` int(10) unsigned NOT NULL,
  `issuer_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sha1_hash` varchar(40) NOT NULL DEFAULT '',
  `sha256_hash` varchar(64) NOT NULL DEFAULT '',
  `serial_number` varchar(40) NOT NULL DEFAULT '',
  `key_type` enum('','RSA','DSA','DH','EC') NOT NULL DEFAULT '',
  `key_size` smallint(5) unsigned NOT NULL DEFAULT 0,
  `issue_date_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_from_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_to_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `subject_cn` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_org` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_ou` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `subject_state` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_locale` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_country` varchar(4) DEFAULT '',
  `subject_jur` varchar(255) DEFAULT '',
  `subject_addr` varchar(255) DEFAULT '',
  `subject_key_id` varchar(40) DEFAULT '',
  `sig_hash` enum('other','md5','sha1','sha256','sha384','sha512','sha256ecdsa','sha384ecdsa','sha512ecdsa') NOT NULL DEFAULT 'other',
  `ku` set('digitalSignature','nonRepudiation','keyEncipherment','dataEncipherment','keyAgreement','keyCertSign','cRLSign','encipherOnly','decipherOnly','critical') NOT NULL DEFAULT '',
  `eku` set('other','critical','serverAuth','clientAuth','codeSigning','emailProtection','anyExtendedKeyUsage','timeStamping','ocspSigning','ipsecEndSystem','ipsecTunnel','ipsecUser','ipsecProtection','ipsecIKE','nsSGC','msSGC','msEFS','msSmartcardLogin','msCTLSign','msCodeInd','msCodeCom','msDocSigning','keyPurposeKdc','intelAMTProvisioning') NOT NULL DEFAULT '',
  `validation` enum('OTHER','OV','OVCF','EV') NOT NULL DEFAULT 'OTHER',
  `cert_type` varchar(6) GENERATED ALWAYS AS (case when find_in_set('serverAuth',`eku`) then 'SSL' when find_in_set('codeSigning',`eku`) then 'CS' when find_in_set('emailProtection',`eku`) then 'SMIME' when `eku` = 'clientAuth' then 'CLIENT' else 'OTHER' end) VIRTUAL,
  `crl_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `ocsp_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `policies_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sans` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `issuer_id` (`issuer_id`),
  KEY `serial_number` (`serial_number`(8)),
  KEY `issue_date_gmt` (`issue_date_gmt`),
  KEY `valid_from_gmt` (`valid_from_gmt`),
  KEY `valid_to_gmt` (`valid_to_gmt`),
  KEY `validation` (`validation`),
  KEY `subject_country` (`subject_country`(2)),
  KEY `subject_org` (`subject_org`(8)),
  KEY `subject_cn` (`subject_cn`(8)),
  KEY `sha1_hash` (`sha1_hash`(8)),
  KEY `sha256_hash` (`sha256_hash`(8)),
  KEY `_idx_cert_type` (`cert_type`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `xcerts_2020` (
  `id` int(10) unsigned NOT NULL,
  `issuer_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sha1_hash` varchar(40) NOT NULL DEFAULT '',
  `sha256_hash` varchar(64) NOT NULL DEFAULT '',
  `serial_number` varchar(40) NOT NULL DEFAULT '',
  `key_type` enum('','RSA','DSA','DH','EC') NOT NULL DEFAULT '',
  `key_size` smallint(5) unsigned NOT NULL DEFAULT 0,
  `issue_date_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_from_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_to_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `subject_cn` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_org` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_ou` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `subject_state` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_locale` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_country` varchar(4) DEFAULT '',
  `subject_jur` varchar(255) DEFAULT '',
  `subject_addr` varchar(255) DEFAULT '',
  `subject_key_id` varchar(40) DEFAULT '',
  `sig_hash` enum('other','md5','sha1','sha256','sha384','sha512','sha256ecdsa','sha384ecdsa','sha512ecdsa') NOT NULL DEFAULT 'other',
  `ku` set('digitalSignature','nonRepudiation','keyEncipherment','dataEncipherment','keyAgreement','keyCertSign','cRLSign','encipherOnly','decipherOnly','critical') NOT NULL DEFAULT '',
  `eku` set('other','critical','serverAuth','clientAuth','codeSigning','emailProtection','anyExtendedKeyUsage','timeStamping','ocspSigning','ipsecEndSystem','ipsecTunnel','ipsecUser','ipsecProtection','ipsecIKE','nsSGC','msSGC','msEFS','msSmartcardLogin','msCTLSign','msCodeInd','msCodeCom','msDocSigning','keyPurposeKdc','intelAMTProvisioning') NOT NULL DEFAULT '',
  `validation` enum('OTHER','OV','OVCF','EV') NOT NULL DEFAULT 'OTHER',
  `cert_type` varchar(6) GENERATED ALWAYS AS (case when find_in_set('serverAuth',`eku`) then 'SSL' when find_in_set('codeSigning',`eku`) then 'CS' when find_in_set('emailProtection',`eku`) then 'SMIME' when `eku` = 'clientAuth' then 'CLIENT' else 'OTHER' end) VIRTUAL,
  `crl_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `ocsp_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `policies_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sans` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `issuer_id` (`issuer_id`),
  KEY `serial_number` (`serial_number`(8)),
  KEY `issue_date_gmt` (`issue_date_gmt`),
  KEY `valid_from_gmt` (`valid_from_gmt`),
  KEY `valid_to_gmt` (`valid_to_gmt`),
  KEY `validation` (`validation`),
  KEY `subject_country` (`subject_country`(2)),
  KEY `subject_org` (`subject_org`(8)),
  KEY `subject_cn` (`subject_cn`(8)),
  KEY `sha1_hash` (`sha1_hash`(8)),
  KEY `sha256_hash` (`sha256_hash`(8)),
  KEY `policies_id` (`policies_id`),
  KEY `_idx_cert_type` (`cert_type`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `xcerts_2021` (
  `id` int(10) unsigned NOT NULL,
  `issuer_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sha1_hash` varchar(40) NOT NULL DEFAULT '',
  `sha256_hash` varchar(64) NOT NULL DEFAULT '',
  `serial_number` varchar(40) NOT NULL DEFAULT '',
  `key_type` enum('','RSA','DSA','DH','EC') NOT NULL DEFAULT '',
  `key_size` smallint(5) unsigned NOT NULL DEFAULT 0,
  `issue_date_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_from_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `valid_to_gmt` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `subject_cn` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_org` varchar(128) CHARACTER SET utf8 DEFAULT '',
  `subject_ou` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `subject_state` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_locale` varchar(96) CHARACTER SET utf8 DEFAULT '',
  `subject_country` varchar(4) DEFAULT '',
  `subject_jur` varchar(255) DEFAULT '',
  `subject_addr` varchar(255) DEFAULT '',
  `subject_key_id` varchar(40) DEFAULT '',
  `sig_hash` enum('other','md5','sha1','sha256','sha384','sha512','sha256ecdsa','sha384ecdsa','sha512ecdsa') NOT NULL DEFAULT 'other',
  `ku` set('digitalSignature','nonRepudiation','keyEncipherment','dataEncipherment','keyAgreement','keyCertSign','cRLSign','encipherOnly','decipherOnly','critical') NOT NULL DEFAULT '',
  `eku` set('other','critical','serverAuth','clientAuth','codeSigning','emailProtection','anyExtendedKeyUsage','timeStamping','ocspSigning','ipsecEndSystem','ipsecTunnel','ipsecUser','ipsecProtection','ipsecIKE','nsSGC','msSGC','msEFS','msSmartcardLogin','msCTLSign','msCodeInd','msCodeCom','msDocSigning','keyPurposeKdc','intelAMTProvisioning') NOT NULL DEFAULT '',
  `validation` enum('OTHER','OV','OVCF','EV') NOT NULL DEFAULT 'OTHER',
  `cert_type` varchar(6) GENERATED ALWAYS AS (case when find_in_set('serverAuth',`eku`) then 'SSL' when find_in_set('codeSigning',`eku`) then 'CS' when find_in_set('emailProtection',`eku`) then 'SMIME' when `eku` = 'clientAuth' then 'CLIENT' else 'OTHER' end) VIRTUAL,
  `crl_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `ocsp_url_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `policies_id` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sans` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `issuer_id` (`issuer_id`),
  KEY `serial_number` (`serial_number`(8)),
  KEY `issue_date_gmt` (`issue_date_gmt`),
  KEY `valid_from_gmt` (`valid_from_gmt`),
  KEY `valid_to_gmt` (`valid_to_gmt`),
  KEY `validation` (`validation`),
  KEY `subject_country` (`subject_country`(2)),
  KEY `subject_org` (`subject_org`(8)),
  KEY `subject_cn` (`subject_cn`(8)),
  KEY `sha1_hash` (`sha1_hash`(8)),
  KEY `sha256_hash` (`sha256_hash`(8)),
  KEY `_idx_cert_type` (`cert_type`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `xcert_crl_urls` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `entry` varchar(200) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=30331 DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `xcert_ocsp_urls` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `entry` varchar(200) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20022 DEFAULT CHARSET=ascii;

CREATE TABLE IF NOT EXISTS `xcert_policies` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `entry` mediumtext DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=40202 DEFAULT CHARSET=ascii;

DROP TABLE IF EXISTS `v_certs_issued_weekly`;
CREATE VIEW `v_certs_issued_weekly` AS  ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
